// Character Server configuration
userid: s1
passwd: p1
server_name: Oasis
login_ip: 127.0.0.1
login_port: 6900
char_ip: 127.0.0.1
char_port: 6121
char_db_ip: 127.0.0.1
char_db_port: 3306
char_db_id: root
char_db_pw: 
char_db_db: oasis_db
